### ISSUE TITLE
CI: Add macOS arm build 

### ISSUE THREAD

**Issue by shinra-electric** [wheremyfoodat/Panda3DS#588]
I tried building Panda3DS locally for Arm, and the results were better than the official x86 build. 

So I took a look at the CI and I think that the only thing to do to create an arm64 artifact is just to change `runs-on: macos-13` to either `runs-on: macos-14` or `runs-on: macos-latest`, as these are both arm64 runners. 

Of course this would replace the Intel build, leaving no build for x86 users, which is probably not desirable. 

Duplicating the job and appending the architecture type to the artifact name would be a good solution, but then this would require changes to the downloads page of the website (and likely more changes elsewhere). 

Having two builds is the simpler solution, but the ideal solution would be to create a universal app bundle. However, I'm not too familiar with that process (I could learn though...)

What do the devs think?

**Comment by wheremyfoodat** [comment]
> Of course this would replace the Intel build, leaving no build for x86 users, which is probably not desirable.
Indeed

> Having two builds is the simpler solution
Given that people have tried to open the executable with a text editor before, the problem here is that they absolutely can't be trusted with downloading the correct build.

> but the ideal solution would be to create a universal app bundle
Which is fairly non-trivial to do here due to the way CMake handles cross-compilation on MacOS (CMAKE_OSX_ARCHITECTURES) being fairly awful and unintuitive to plug into an existing codebase.

**Comment by wheremyfoodat** [comment]
Builds are now universal, thus closing this issue.
