### ISSUE TITLE
Can't Download from website with a chromium browser

### ISSUE THREAD

**Issue by loglot** [wheremyfoodat/Panda3DS#705]
on the website, i am unable to download the emulator due to chromium browsers detecting it as a virus, there is a chance that if you didn't call it `"Windows executible.zip"` this wouldn't happen, please consider renaming the zip file on the website
![image](https://github.com/user-attachments/assets/e4a1cabc-4199-494a-86de-1dd8c6d836c6)

**Comment by wheremyfoodat** [comment]
This is not happening because of the filename, Chromium actually throws the executable inside the zip at Windows Defender, which is way too eager to label things as viruses with its ML-based filters. This is why it is only marked as a virus when the download finishes. Release builds suffer from this problem less as they're downloaded by more people than the average nightly.

Though yeah I'll probably change the namea due other issues such as users not knowing which one they've downloaded. It's a mild pain to change the names though as all download links need to be changed, including ones in the repo, the website, and other third-party websites.
